PRAGMA foreign_keys = OFF;
DELETE FROM recipes;
DELETE FROM raw_materials;
INSERT INTO raw_materials (id, name, current_stock, unit_measure, min_stock_alert, average_cost_per_unit, preferred_supplier_id) VALUES (1, 'Harina de Trigo', 50, 'kg', 10, 1.2, 1);
INSERT INTO raw_materials (id, name, current_stock, unit_measure, min_stock_alert, average_cost_per_unit, preferred_supplier_id) VALUES (2, 'Mantequilla Sin Sal', 30, 'kg', 5, 8.5, 2);
INSERT INTO raw_materials (id, name, current_stock, unit_measure, min_stock_alert, average_cost_per_unit, preferred_supplier_id) VALUES (3, 'Azúcar Blanca', 40, 'kg', 8, 1.1, 3);
INSERT INTO raw_materials (id, name, current_stock, unit_measure, min_stock_alert, average_cost_per_unit, preferred_supplier_id) VALUES (4, 'Azúcar Moreno', 25, 'kg', 5, 1.5, 1);
INSERT INTO raw_materials (id, name, current_stock, unit_measure, min_stock_alert, average_cost_per_unit, preferred_supplier_id) VALUES (5, 'Chispas de Chocolate', 20, 'kg', 4, 12, 2);
INSERT INTO raw_materials (id, name, current_stock, unit_measure, min_stock_alert, average_cost_per_unit, preferred_supplier_id) VALUES (6, 'Huevos', 500, 'unidades', 100, 0.15, 3);
INSERT INTO raw_materials (id, name, current_stock, unit_measure, min_stock_alert, average_cost_per_unit, preferred_supplier_id) VALUES (7, 'Cacao en Polvo', 10, 'kg', 2, 15, 1);
INSERT INTO raw_materials (id, name, current_stock, unit_measure, min_stock_alert, average_cost_per_unit, preferred_supplier_id) VALUES (8, 'Extracto de Vainilla', 5, 'L', 1, 25, 2);
INSERT INTO raw_materials (id, name, current_stock, unit_measure, min_stock_alert, average_cost_per_unit, preferred_supplier_id) VALUES (9, 'Levadura', 2, 'kg', 0.5, 5, 3);
INSERT INTO raw_materials (id, name, current_stock, unit_measure, min_stock_alert, average_cost_per_unit, preferred_supplier_id) VALUES (10, 'Sal Fina', 5, 'kg', 1, 0.8, 1);
INSERT INTO raw_materials (id, name, current_stock, unit_measure, min_stock_alert, average_cost_per_unit, preferred_supplier_id) VALUES (11, 'Matcha Premium', 2, 'kg', 0.5, 45, 2);
INSERT INTO raw_materials (id, name, current_stock, unit_measure, min_stock_alert, average_cost_per_unit, preferred_supplier_id) VALUES (12, 'Nueces Picadas', 5, 'kg', 1, 18, 3);
INSERT INTO raw_materials (id, name, current_stock, unit_measure, min_stock_alert, average_cost_per_unit, preferred_supplier_id) VALUES (13, 'Café Grano', 15, 'kg', 3, 22, 1);
INSERT INTO raw_materials (id, name, current_stock, unit_measure, min_stock_alert, average_cost_per_unit, preferred_supplier_id) VALUES (14, 'Leche Entera', 100, 'L', 20, 1.2, 2);
INSERT INTO recipes (product_id, material_id, quantity_needed) VALUES (1, 1, 0.05);
INSERT INTO recipes (product_id, material_id, quantity_needed) VALUES (1, 2, 0.03);
INSERT INTO recipes (product_id, material_id, quantity_needed) VALUES (1, 4, 0.02);
INSERT INTO recipes (product_id, material_id, quantity_needed) VALUES (1, 5, 0.025);
INSERT INTO recipes (product_id, material_id, quantity_needed) VALUES (1, 6, 0.2);
INSERT INTO recipes (product_id, material_id, quantity_needed) VALUES (2, 1, 0.04);
INSERT INTO recipes (product_id, material_id, quantity_needed) VALUES (2, 2, 0.03);
INSERT INTO recipes (product_id, material_id, quantity_needed) VALUES (2, 4, 0.025);
INSERT INTO recipes (product_id, material_id, quantity_needed) VALUES (2, 6, 0.2);
INSERT INTO recipes (product_id, material_id, quantity_needed) VALUES (4, 1, 0.06);
INSERT INTO recipes (product_id, material_id, quantity_needed) VALUES (4, 2, 0.04);
INSERT INTO recipes (product_id, material_id, quantity_needed) VALUES (4, 3, 0.03);
INSERT INTO recipes (product_id, material_id, quantity_needed) VALUES (4, 6, 0.2);
INSERT INTO recipes (product_id, material_id, quantity_needed) VALUES (5, 1, 0.045);
INSERT INTO recipes (product_id, material_id, quantity_needed) VALUES (5, 2, 0.03);
INSERT INTO recipes (product_id, material_id, quantity_needed) VALUES (5, 7, 0.015);
INSERT INTO recipes (product_id, material_id, quantity_needed) VALUES (5, 5, 0.02);
INSERT INTO recipes (product_id, material_id, quantity_needed) VALUES (5, 6, 0.2);
INSERT INTO recipes (product_id, material_id, quantity_needed) VALUES (9, 1, 0.05);
INSERT INTO recipes (product_id, material_id, quantity_needed) VALUES (9, 11, 0.005);
INSERT INTO recipes (product_id, material_id, quantity_needed) VALUES (9, 2, 0.03);
INSERT INTO recipes (product_id, material_id, quantity_needed) VALUES (9, 3, 0.025);
INSERT INTO recipes (product_id, material_id, quantity_needed) VALUES (12, 1, 0.03);
INSERT INTO recipes (product_id, material_id, quantity_needed) VALUES (12, 2, 0.05);
INSERT INTO recipes (product_id, material_id, quantity_needed) VALUES (12, 7, 0.04);
INSERT INTO recipes (product_id, material_id, quantity_needed) VALUES (12, 3, 0.06);
INSERT INTO recipes (product_id, material_id, quantity_needed) VALUES (12, 6, 0.5);
INSERT INTO recipes (product_id, material_id, quantity_needed) VALUES (15, 1, 0.03);
INSERT INTO recipes (product_id, material_id, quantity_needed) VALUES (15, 2, 0.05);
INSERT INTO recipes (product_id, material_id, quantity_needed) VALUES (15, 7, 0.04);
INSERT INTO recipes (product_id, material_id, quantity_needed) VALUES (15, 12, 0.02);
INSERT INTO recipes (product_id, material_id, quantity_needed) VALUES (15, 6, 0.5);
INSERT INTO recipes (product_id, material_id, quantity_needed) VALUES (3, 13, 0.018);
INSERT INTO recipes (product_id, material_id, quantity_needed) VALUES (6, 13, 0.018);
INSERT INTO recipes (product_id, material_id, quantity_needed) VALUES (6, 14, 0.2);
PRAGMA foreign_keys = ON;
