PRAGMA foreign_keys = OFF;
DELETE FROM daily_operations;
DELETE FROM recipes;
DELETE FROM products;
INSERT INTO products (name, category, price) VALUES ('Panecillos', 'Bollería', 1.2);
INSERT INTO products (name, category, price) VALUES ('Coca Vidrio', 'Bollería', 3.2);
INSERT INTO products (name, category, price) VALUES ('Berlina Rellena', 'Bollería', 3.5);
INSERT INTO products (name, category, price) VALUES ('Mini Palmerita Petit Doré', 'Bollería', 2.8);
INSERT INTO products (name, category, price) VALUES ('Mini Palmerita Chocolate', 'Bollería', 2.95);
INSERT INTO products (name, category, price) VALUES ('Barra Granier', 'Panadería', 1.3);
INSERT INTO products (name, category, price) VALUES ('Tartita Manzana', 'Bollería', 3.5);
INSERT INTO products (name, category, price) VALUES ('Mini Dots', 'Bollería', 2.5);
INSERT INTO products (name, category, price) VALUES ('Dots Negrito', 'Bollería', 1.8);
INSERT INTO products (name, category, price) VALUES ('Big Dots Sucré', 'Bollería', 3.2);
INSERT INTO products (name, category, price) VALUES ('Magdalena', 'Bollería', 2.8);
INSERT INTO products (name, category, price) VALUES ('Palmeritas Cereales', 'Bollería', 2.2);
INSERT INTO products (name, category, price) VALUES ('Mini Croissant Mantequilla', 'Bollería', 2.75);
INSERT INTO products (name, category, price) VALUES ('Plum Cake', 'Bollería', 3.95);
INSERT INTO products (name, category, price) VALUES ('Croissant Cereales', 'Bollería', 3.75);
INSERT INTO products (name, category, price) VALUES ('Croissant Margarina', 'Bollería', 3.2);
INSERT INTO products (name, category, price) VALUES ('Croissant Mantequilla', 'Bollería', 3.2);
INSERT INTO products (name, category, price) VALUES ('Fartons', 'Bollería', 1.95);
INSERT INTO products (name, category, price) VALUES ('Cookie Doble Choco', 'Bollería', 1.95);
INSERT INTO products (name, category, price) VALUES ('Napolitana Chocolate', 'Bollería', 1.95);
INSERT INTO products (name, category, price) VALUES ('Napolitana Crema', 'Bollería', 1.95);
INSERT INTO products (name, category, price) VALUES ('Cañas', 'Bollería', 3.2);
INSERT INTO products (name, category, price) VALUES ('Tulipe Red Velvet', 'Bollería', 1.95);
INSERT INTO products (name, category, price) VALUES ('Tulipe Carrot Cake', 'Bollería', 1.95);
INSERT INTO products (name, category, price) VALUES ('Croissant Argentino', 'Bollería', 3.2);
INSERT INTO products (name, category, price) VALUES ('Rollito Choco Petit Doré', 'Bollería', 2.95);
INSERT INTO products (name, category, price) VALUES ('Granierito', 'Bollería', 2.5);
INSERT INTO products (name, category, price) VALUES ('Bizcocho', 'Bollería', 2.6);
INSERT INTO products (name, category, price) VALUES ('Croissant Relleno Almendra', 'Bollería', 2.2);
INSERT INTO products (name, category, price) VALUES ('Croissant Relleno Cheesecake', 'Bollería', 2.2);
INSERT INTO products (name, category, price) VALUES ('Croissant Relleno Pistacho', 'Bollería', 2.2);
INSERT INTO products (name, category, price) VALUES ('Tarta Chocolate Sacher', 'Pastelería', 4.65);
INSERT INTO products (name, category, price) VALUES ('Tarta San Marcos', 'Pastelería', 4.5);
INSERT INTO products (name, category, price) VALUES ('Tarta Selva Negra', 'Pastelería', 4.5);
INSERT INTO products (name, category, price) VALUES ('Tarta Zanahoria', 'Pastelería', 4.65);
INSERT INTO products (name, category, price) VALUES ('Tarta Americana Chocolate', 'Pastelería', 4.65);
INSERT INTO products (name, category, price) VALUES ('Tarta Queso con Frambuesa', 'Pastelería', 4.65);
INSERT INTO products (name, category, price) VALUES ('Tarta Manzana', 'Pastelería', 4.65);
INSERT INTO products (name, category, price) VALUES ('Pincho Tortilla', 'Salado', 3.2);
INSERT INTO products (name, category, price) VALUES ('Croissant Vegetal', 'Salado', 2.95);
INSERT INTO products (name, category, price) VALUES ('Bocadillo Vegetal Atún', 'Salado', 3.95);
INSERT INTO products (name, category, price) VALUES ('Bocadillo Pollo', 'Salado', 3.95);
INSERT INTO products (name, category, price) VALUES ('Croissant York y Queso', 'Salado', 2.95);
INSERT INTO products (name, category, price) VALUES ('Bocadillo Grande Jamón Ibérico', 'Salado', 4.95);
INSERT INTO products (name, category, price) VALUES ('Pizza Focaccia', 'Salado', 4.95);
INSERT INTO products (name, category, price) VALUES ('Empanadillas', 'Salado', 3.5);
PRAGMA foreign_keys = ON;
